[package]
name = "apty_npm_parallel"
version = "0.1.0"
authors = ["saiumesh-apty"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
